image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get install -y openjdk-11-jdk

test:cargo:
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose
